### ISSUE TITLE
static.xx.fbcdn.net

### ISSUE THREAD

**Issue by funilrys** [Ultimate-Hosts-Blacklist/smed79_blocklist_facebook#1]
Hey @smed79,

What's your input on `static.xx.fbcdn.net`? 

If you think that we should keed it I'm ready to create and append it to a `social` or `facebook` section of the whitelist lists we can propose ==> https://github.com/Ultimate-Hosts-Blacklist/dev-center/tree/whitelisting/data. If you want to participate there let me know so that I can add you write access there too :smile_cat: 

Let me know what you think about this when you have time.

Have a nice day/night.

Cheers,
Nissar

**Comment by smed79** [comment]
Hi, 
what is the issue with this FB server?

**Comment by funilrys** [comment]
My bad false domain :joy: Keep up the good work :+1:
